### ISSUE TITLE
CreateStack as true is deploying to other region(s) without the deployment package uploaded to corresponding region's S3 bucket

### ISSUE THREAD

**Issue by malli1246** [rrahul963/serverless-create-global-dynamodb-table#17]
I tried to setup a multi region serverless app which has a Lambda function that serves api requests and uses DynamoDB. 

While deploying thru CI/CD tool for one of the region, 

1. Global Table scripts started execution after the completion of stack updates for one of the desired regions. 
2. Next, script started creating/updating stack of other region without uploading the artifacts/deployment package to next region. 
3. The stack creation failed saying that the S3Key(path to package) as **NoSuckKey** and the Lambda deployment is failing causing the stack to rollback.

Please find the screenshots below for the stack updates verbose and the aws CFN error event from my sample project. Here, I tried to deploy to the default region but has two regions under custom node.

![image](https://user-images.githubusercontent.com/24697608/72003784-1fd4ff00-3270-11ea-9b40-7b659a5421ef.png)
![image](https://user-images.githubusercontent.com/24697608/72004015-878b4a00-3270-11ea-8878-8bca46242ca8.png)

Didn't face any issue if there is no lambda to be created in the stack as the Lambda creation has a constraint that the deployment package should be in the same region.

Due to my delivery deadlines, had to search if there is a way and found another package for creating global table which just creates a table and create a replication for the same.

Any updates or any suggestions related to this issue is much appreciated

serverless.yml:
```

service: my-auth-service-globaltable-issue

plugins:
      - serverless-create-global-dynamodb-table

custom:
  globalTables:
    regions: # list of regions in which you want to set up global tables
      - us-east-1
      - us-west-2
    createStack: true
    tags: # List of tags that needs to applied to the new table (optional)
      - Key: tag-key
        Value: tag-value
      - Key: tag-key-2
        Value: tag-value-2

provider:
  name: aws
  runtime: python3.8
  
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeStream
        - dynamodb:GetRecords
        - dynamodb:GetShardIterator
        - dynamodb:ListStreams
      Resource: arn:aws:dynamodb:*:*:table/usersTable-final
      # you can overwrite defaults here
  stage: dev
  region: us-east-1

functions:
  hello-final:
    handler: handler.hello

resources: # CloudFormation template syntax
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table      
      Properties:
        TableName: usersTable-globaltable-issue
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: email
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 3
          WriteCapacityUnits: 3
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
```
