### ISSUE TITLE
How can I customize stack name?

### ISSUE THREAD

**Issue by zhaoyi0113** [rrahul963/serverless-create-global-dynamodb-table#20]
First, thanks for releasing this awesome library. I have a feature request for stack name used in https://github.com/rrahul963/serverless-create-global-dynamodb-table/blob/40ad7ba07516d0cc96a39f62f36afb1a9310595e/src/helper.js#L356.

In my serverless.yml file, I am not using the stack name as `serviceName-stageName`.  Below is my configuration:
```
provider:
  name: aws
  runtime: nodejs12.x
  region: ${opt:region}
  stackName: ${opt:stage}-${self:service.name}
```

If I use above configuration, I will get an error `Failed to setup global table. Error Stack with id dbs-api-dev does not exist`. `dev` is my stage name. 
I think this is because the code doesn't read stack name from my serverless. Can you make it read from `serverless` configuration?
