### ISSUE TITLE
Failed to create global table with v1

### ISSUE THREAD

**Issue by zhaoyi0113** [rrahul963/serverless-create-global-dynamodb-table#44]
I have blow configuration:

```
globalTables:
    version: v2
    regions:
      - ap-southeast-1
      - ap-southeast-2
    createStack: false
```
but when run `sls deploy` in ap-southeast-2, it gives me below error

```
CreateGlobalTable: Failed to setup global table. Error Cannot add, delete, or update the local region through ReplicaUpdates. Use CreateTable, DeleteTable, or UpdateTable as required.
```

what could be the reason causing this issue?
